version: "3"

services: 

    db:
        image: postgres
        container_name: db
        restart: always
        ports: 
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: db_ecoleta
        logging: 
            driver: "json-file"
            options: 
                max-size: "10m"
                max-file: "5"

    # pgadmin:
    #     image: dpage/pgadmin4
    #     restart: always
    #     environment: 
    #         PGADMIN_DEFAULT_EMAIL: postgres
    #         PGADMIN_DEFAULT_PASSWORD: postgres
    #     ports:
    #         - 8080:80
    #     depends_on:
    #         - db
    #     networks:
    #         - postgres-network

    server:
        image: node:12.18
        container_name: server
        restart: always
        volumes: 
            - ./server/:/usr/app/
        working_dir: /usr/app/
        ports: 
            - "3333:3333"
        depends_on: 
            - db
        command: npm start
        environment: 
            - NODE_ENV=development
        tty: true
        logging: 
            driver: "json-file"
            options: 
                max-size: "10m"
                max-file: "5"
        
    
    web:
        image: node:12.18
        container_name: web
        restart: always
        volumes: 
            - ./web/:/usr/app/
        working_dir: /usr/app/
        ports: 
            - "3000:3000"
        depends_on: 
            - server
        command: npm start
        tty: true
        logging: 
            driver: "json-file"
            options: 
                max-size: "10m"
                max-file: "5"

    # mobile:
    #     image: bycedric/expo-cli:3
    #     container_name: mobile
    #     restart: always
    #     volumes: 
    #         - ./mobile/:/usr/app/
    #     working_dir: /usr/app/
    #     ports: 
    #         - "19002:19002"
    #         - "19001:19001"
    #         - "19000:19000"
    #     depends_on: 
    #         - server
    #     command: npm start
    #     tty: true
    #     logging: 
    #         driver: "json-file"
    #         options: 
    #             max-size: "10m"
    #             max-file: "5"